Repository didi/mand-mobile, pull requests merged in 2018-07, with the labels that each got.

#127 fix(radio):fix icon unnecessary left/right spacing #126
  components/radio/index.vue
Labels: bug

#133 fix(input-item):add numeric type of value
  components/input-item/index.vue
Labels: P0, bug

#130 fix(picker):given a default itemIndex when both defaultIndex & default…
  components/picker/picker-column.vue
Labels: P0, bug

#137 fix(cashier):fix cashier success icon style
  components/cashier/index.vue
Labels: bug

#142 replace ** with Math.pow
  components/_util/lang.js
  components/field-item/index.vue
Labels: P0, bug

#146 fix: auto install[#141]
  components/index.js
Labels: bug

#147 feat(check): add check-group component
  components/_style/mixin/theme.styl
  components/check-box/README.en-US.md
  components/check-box/README.md
  components/check-box/component.js
  components/check-box/demo/cases/demo0.vue
  components/check-box/demo/cases/demo1.vue
  components/check-box/demo/index.vue
  components/check-box/index.vue
  components/check-box/test/index.spec.js
  components/check-group/README.en-US.md
  components/check-group/README.md
  components/check-group/component.js
  components/check-group/demo/cases/demo0.vue
  components/check-group/demo/cases/demo1.vue
  components/check-group/demo/cases/demo2.vue
  components/check-group/demo/index.vue
  components/check-group/index.vue
  components/check-group/test/index.spec.js
  components/check-list/README.en-US.md
  components/check-list/README.md
  components/check-list/component.js
  components/check-list/demo/cases/demo0.vue
  components/check-list/demo/cases/demo1.vue
  components/check-list/demo/index.vue
  components/check-list/index.vue
  components/check-list/test/index.spec.js
  components/index.js
  examples/components.json
  examples/demo-index.indemand.js
  examples/demo-index.js
Labels: feature

#145 feat(tab-bar): add scrollable support #144
  components/tab-bar/demo/cases/demo10.vue
  components/tab-bar/demo/index.vue
  components/tab-bar/index.vue
Labels: feature

#152 fix(swiper): fixed not autoplay when created swiper-item by async dat…
  components/swiper/demo/cases/demo0.vue
  components/swiper/index.vue
Labels: bug

#156 doc: Improve component readme
  components/check-box/README.en-US.md
  components/check-box/README.md
  components/check-group/README.en-US.md
  components/check-group/README.md
  components/check-list/README.en-US.md
  components/check-list/README.md
Labels: doc

#155 fix: Improve type definitions[#153]
  types/action-sheet.d.ts
  types/dialog.d.ts
  types/index.d.ts
  types/toast.d.ts
Labels: bug

#161 fix(image-reader):fix image files length for close worker
  components/image-reader/index.vue
Labels: P1, bug

#163 fix(dialog): text align center only if there has one line
  components/dialog/dialog.vue
Labels: bug
