Repository didi/mand-mobile, pull requests merged in 2018-06, with the labels that each got.

#109 feature(cashier):more text configurable
  components/cashier/README.md
  components/cashier/demo/cases/demo0.vue
  components/cashier/index.vue
Labels: P0

#106 build:add css bundle using css variables to release
  build/rollup/build-component.rollup.js
  build/rollup/build-mand-mobile.rollup.js
  build/rollup/rollup-plugin-config.js
  build/stylus-mixin.js
  package.json
Labels: P1

#118 fix(agree): flexbox display bug
  components/agree/demo/cases/demo0.vue
  components/agree/index.vue
Labels: bug

#115 feat(dialog): add static method "closeAll"
  components/dialog/README.en-US.md
  components/dialog/README.md
  components/dialog/index.js
  components/dialog/test/index.spec.js
Labels: feature

#119 feature(activity-indicator):add activity_indicator
  components/activity-indicator/README.en-US.md
  components/activity-indicator/README.md
  components/activity-indicator/carousel-circle.vue
  components/activity-indicator/carousel.vue
  components/activity-indicator/component.js
  components/activity-indicator/demo/cases/demo0.vue
  components/activity-indicator/demo/cases/demo1.vue
  components/activity-indicator/demo/cases/demo2.vue
  components/activity-indicator/demo/index.vue
  components/activity-indicator/index.vue
  components/activity-indicator/roller-success.vue
  components/activity-indicator/roller.vue
  components/activity-indicator/spinner.vue
  components/activity-indicator/test/index.spec.js
  components/cashier/index.vue
  components/cashier/rolling.vue
  components/index.js
  examples/components.json
  examples/demo-index.js
Labels: feature

#117 feat(action-sheet): Add static methods support #79
  components/action-sheet/README.en-US.md
  components/action-sheet/README.md
  components/action-sheet/action-sheet.vue
  components/action-sheet/index.js
  components/action-sheet/test/index.spec.js
Labels: feature

#116 feature(amount):add amount
  components/_util/animate.js
  components/_util/scroller.js
  components/amount/README.en-US.md
  components/amount/README.md
  components/amount/demo/cases/demo0.vue
  components/amount/demo/cases/demo1.vue
  components/amount/demo/cases/demo2.vue
  components/amount/demo/cases/demo3.vue
  components/amount/demo/index.vue
  components/amount/index.vue
  components/amount/number-capital.js
  components/amount/test/index.spec.js
  components/index.js
  examples/components.json
  examples/demo-index.js
  site/theme/default/Preview.vue
Labels: feature
